# Site settings

url: "http://lua.org.pl" # the base hostname & protocol for your site
date: 2015-12-31

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
