# Site settings

url: "https://lua.org.pl" # the base hostname & protocol for your site
date: 2022-11-10

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
